<?php
// **********************************************************************************
// **                                                                              **
// ** menu.inc                                      (c) Wolfram Plettscher 03/2015 **
// **                                                                              **
// **********************************************************************************

/*    <script src="https://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
*/

echo ('
	<!-- following lines are included for menu style -->
    <link rel="stylesheet" href="css/menu.css">
    <script src="./inc/jquery-2.1.3.min.js" type="text/javascript"></script>
    <script src="script.js"></script>
       '); 
?>