<?php
// **********************************************************************************
// **                                                                              **
// ** selectbox.inc                                 (c) Wolfram Plettscher 01/2015 **
// **                                                                              **
// **********************************************************************************
?>
<style type='text/css'>

.selectbox {

	background: #516eb1;
	color: #ffffff;
	text-align: left;
//	font-weight: bold;
	font-size: 12px;
	border-style: none;
   }

</style>
