<?php
// **********************************************************************************
// **                                                                              **
// ** index.php                                     (c) Wolfram Plettscher 10/2014 **
// **                                                                              **
// **********************************************************************************

include ('auth.php');
?>

<?php
	if (isset ($_GET["section"]))
		{
			$section = $_GET["section"];
		} else {
			$section = "";
		}
?>


<html>
    <head>
		<!-- following lines are included for menu style -->
        <link rel="stylesheet" href="css/menu.css">
        <script src="http://code.jquery.com/jquery-latest.min.js" type="text/javascript"></script>
        <script src="script.js"></script>
        
        <title>HTML5 page</title>
        <link href="css/style.css" rel="stylesheet" type="text/css">

		<!-- add script for zebra-table -->
		<sript src="jquery.js"></script>
        <script>
		$(function(){
//			$('#cssmenu').hide().fadeIn(4000);
			$('.sqltable tr:first-child').addClass('sqltableone');
			$('.sqltable tr:nth-child(even)').addClass('sqltableeven');
			$('.sqltable tr:nth-child(2n+3)').addClass('sqltableodd');
			});
		</script>

<style type="text/css">
.css_btn_class {
  background: #516eb1;
//  -webkit-box-shadow: 0 -4px 0 #516eb1, 0 -5px 0 #a6afd6, 0 -6px 0 #516eb1;
//  -moz-box-shadow: 0 -4px 0 #516eb1, 0 -5px 0 #a6afd6, 0 -6px 0 #516eb1;
//  box-shadow: 0 -4px 0 #516eb1, 0 -5px 0 #a6afd6, 0 -6px 0 #516eb1;
  color: #ffffff;
	text-align: left;
//	font-weight:bold;
	font-size: 12px;
	border-style: none;

}
.css_btn_class:hover {
	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #516eb1), color-stop(1, #a6afdf) );
	background:-moz-linear-gradient( center top, #516eb1 5%, #a6afdf 100% );
	filter:progid:DXImageTransform.Microsoft.gradient(startColorstr='#516eb1', endColorstr='#a6afdf');
	background-color:#516eb1;
}.css_btn_class:active {
//	position:relative;
//	top:1px;
}
/* This button was generated using CSSButtonGenerator.com */


p {
	color: #516eb1;
}

}
/* This css button was generated by css-button-generator.com */
</style>

    </head>

<!-- ---------------------------------------------------------------------------- -->
<!-- body                                                                         -->
<!-- ---------------------------------------------------------------------------- -->
    <body>

        <div id="wrapper">

            <div id="header">
            	<table width="980px"><tr>
					<td align="left" valign="bottom"><h3>Wolfram Plettscher's Project Tools</h3></td>
					<td align="right" valign="middle"></td>
				</tr></table>
            </div>
        
            <div id="cssmenu">
				<?php include ("menu.php"); ?>
            </div>
            
            <div id="contentbody">
				<?php include ("sites.php"); ?>
            </div>
            
        </div>

        <div id="footer">
            &copy; Bluefish Communications, Wolfram Plettscher 2014
        </div>
    
    </body>

</html>
