<?php
// **********************************************************************************
// **                                                                              **
// ** globalvars.inc                                (c) Wolfram Plettscher 12/2015 **
// **                                                                              **
// **********************************************************************************

// define global variables for overall configuration etc.
if (!defined ('GLOBALVARS')) {
	define ('GLOBALVARS', 'globalvars');

//	define ('HOSTEUROPE_SSLPROXY', '1');

	}

?>
