<?php
// **********************************************************************************
// **                                                                              **
// ** credentials.inc                               (c) Wolfram Plettscher 12/2015 **
// **                                                                              **
// **********************************************************************************

$username="wptoolsdbadmin";
$password="1L5MT6u4";
$database="wptools";
$host="localhost";
?>
